/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz.app;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author o
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
      Startscreen stscreen;
    String role;
     private Connection connection;
    public Login(Startscreen s,String role) {
        this.stscreen=s;
        this.role=role;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Enter id");

        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });

        loginbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginbtn.setText("LOGIN");
        loginbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        loginbtn.setFocusPainted(false);
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        Cancelbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cancelbtn.setText("Cancel");
        Cancelbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Cancelbtn.setFocusPainted(false);
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn)
                    .addComponent(Cancelbtn))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed

        // TODO add your handling code here:
        String id = userid.getText().trim();
       
        
connection=DatabaseManager.getConnected();
        if (id.isEmpty()) {
            // Display a dialog box if either field is empty
            JOptionPane.showMessageDialog(this, "Please provide your id");
        } else 
        {
            try {
   String query = "";
    
    if (role.equals("Student")) {
        query = "SELECT id,Role FROM students WHERE id = ?";
    } else if (role.equals("Teacher")) {
        query = "SELECT Tid,Role FROM teacher WHERE Tid = ?";
    }
    
    
     PreparedStatement preparedStatement = connection.prepareStatement(query);
    preparedStatement.setString(1, id);
    
    ResultSet resultSet = preparedStatement.executeQuery();

    if (resultSet.next()) {
        JOptionPane.showMessageDialog(this, "User found. Role: " + resultSet.getString("Role"));
     
        String dbRole= resultSet.getString("Role");
        
        if(dbRole.equals("Student")&& role.equals("Student"))
        {
             this.dispose();
//            Questionframe qf=new Questionframe();
            Studentdashboard sd=   new Studentdashboard(userid.getText().trim());
//            qf.setVisible(true);
    sd.setVisible(true);

            
        }
        else if(dbRole.equals("Teacher")&& role.equals("Teacher"))
        {
             this.dispose();
            Teacherframe tf=new Teacherframe(this);
            tf.setVisible(true);
        
        } else
        {
            JOptionPane.showMessageDialog(this, "Role mismatch. Please select the correct login option.");
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "User not found");
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error in executing the query: " + e.getMessage());
}
           
            
           
             
            }
                
            
            // Process the entered data because both fields have values
            // For example, you might proceed with authentication here
            // Your logic to authenticate the user goes here
        

       

    }//GEN-LAST:event_loginbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed

        // TODO add your handling code here:
        this.dispose();
//        DatabaseManager.closeConnection();
        stscreen.setVisible(true);
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
